### ISSUE TITLE
Unable to Uninstall the addon with Blender 3.3.0 

### ISSUE THREAD

**Issue by CassyDaBean** [cgtinker/BlendArMocap#103]
So just as it says on the tin. The Addon really REALLY doesn't like being disabled/uninstalled on Windows 10 on blender version 3.3.0 (Standalone/didn't install it through the webstore or through the installer).

Effectively I installed it properly, got it to work, Everything was fine and dandy. 

Until I tried to remove the dependencies using the "Uninstall Conflicting Packages and shut down blender" button. I took note that it still said the dependencies were still installed, but there's no path, or name attached to them.
I then removed the addon from the Addon list thinking it's fully uninstalled. Now blender just crashes when I try to append ANY of my past models, or when I try to open any models as well...

So this is a major issue. and I'm not even sure if this Git repos page is looked at anymore...

**Comment by MythicSoldier** [comment]
I'm looking at it ;(

**Comment by cgtinker** [comment]
Hm, not really sure if my new update fixes this - I've rewritten a lot. 
As the packaging of mediapipe is kinda a pain to use in blender, I've decided to install the entire tree manually in the new update. (Besides there are huge changes to the transfer). Just pushed it to the main - u can you give it a try. preferably use a new, clean blender version in this case. Let me know how it goes :)

**Comment by MythicSoldier** [comment]
Working before you updated the code and I’m using it well!

**Comment by cgtinker** [comment]
I'll create an official release of the upcoming version next week. If you face any dependency issues please refer to the issues I've created for them
