### ISSUE TITLE
Can't move the hands of the rig

### ISSUE THREAD

**Issue by unswimmingduck** [cgtinker/BlendArMocap#104]
I follow your step in the YouTube, but in my blender when i chose the hand as the target and ues the webcam to detect the hand, it' all ok. But after this steps, when i click the buttom "transfer animation" the hands of the rig didn't move at all.I felt very confused and don't konw what to do to sovle it. I was overwhelmed. I hope you can help me!!!!! Thanks a lot!

**Comment by unswimmingduck** [comment]
OK,I've tackled this problem. I load the 2.93LTS version and download the latest [BlendArMocap-release-152.zip](https://github.com/cgtinker/BlendArMocap/releases/download/v1.5.2/BlendArMocap-release-152.zip). After that every functions work .
Thank you project very much.Your project is really useful and very promising, but I'm extremely hope you can adjust it to be more sutiable to different versions.

**Comment by Tung-Vinh-Long** [comment]
> OK, tôi đã giải quyết vấn đề này. Tôi tải phiên bản 2.93LTS và tải xuống [BlendArMocap-release-152.zip](https://github.com/cgtinker/BlendArMocap/releases/download/v1.5.2/BlendArMocap-release-152.zip) mới nhất . Sau đó, mọi chức năng đều hoạt động. Cảm ơn dự án của bạn rất nhiều. Dự án của bạn thực sự hữu ích và rất hứa hẹn, nhưng tôi rất hy vọng bạn có thể điều chỉnh nó để phù hợp hơn với các phiên bản khác nhau.

Thanks for the guide, it worked for me
