### ISSUE TITLE
python error when transfering animation

### ISSUE THREAD

**Issue by romanties** [cgtinker/BlendArMocap#107]
I captured a motion which i wanted to transfer onto my rigify rig, but its returning this error to me: 
<img width="788" alt="image" src="https://user-images.githubusercontent.com/119822168/205523838-4a411d4a-7605-47c8-bfef-f0221c54ba67.png">
any ideas? could really use some help!

**Comment by JimPansen23** [comment]
Similar Problem here!

In my case the problems are in line 53, 121 and 40 .

I also had problems with the installation of the dependencies. I had to set "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem Set LongPathsEnabled" to 1.

**Comment by dustturtle** [comment]
i got similar issue, key "torso" not found

**Comment by dustturtle** [comment]
@cgtinker

**Comment by cgtinker** [comment]
hey there - either there are some bones missing, renamed or the target is not a generated rigify rig.
I've rewritten the entire transfer setup - as it's a major update it still requires some testing - u might want to give it a try (just pushed it to the main branch - infos in the readme).

**Comment by cgtinker** [comment]
I've updated blendarmocap, you can pull the current version from the main. I'll create an official release next week which fixes issues like that.
