### ISSUE TITLE
After successfully tracking the movement, how to re-target any 3D model?

### ISSUE THREAD

**Issue by Tung-Vinh-Long** [cgtinker/BlendArMocap#108]
I have successfully done the tracking of moving poses. But couldn't find any instructions on retargeting a 3D model. Someone with a link talks about retargeting to use in conjunction with BlendArMocap. Please give me such a link. Thanks in advance for the help.
We have Rokoko and Auto-Rig Pro retargeting methods. But how to use them with BlendMocap ?

**Comment by cgtinker** [comment]
I've rewritten the entire transfer setup - check the main branch and the readme. 
It still requires some testing before I can call it an official release but the update introduces an own way to target other rigs. You might want to give it a go ;)
