### ISSUE TITLE
Face Transfer Rigify

### ISSUE THREAD

**Issue by secretgspot** [cgtinker/BlendArMocap#112]
Everything works fine if you do default rigify face, however if you upgrade it first 
![image](https://user-images.githubusercontent.com/203323/208826910-de4b3b29-7c19-4f27-a1d8-7531f64cb50e.png)

then you get an error
![image](https://user-images.githubusercontent.com/203323/208826972-9f983e8a-7904-415a-809d-0b5d586e694d.png)

**Comment by secretgspot** [comment]
developer doesn't care enough to even acknowledge.. understood.

**Comment by cgtinker** [comment]
It hasn't been supported - ain't a bug..
Soon done with an update to support other rigs
