### ISSUE TITLE
Not able to activate Blend add-ons.

### ISSUE THREAD

**Issue by ausbro80** [cgtinker/BlendArMocap#113]
<img width="384" alt="Screenshot 2022-12-26 at 6 30 36 PM" src="https://user-images.githubusercontent.com/116780283/209532293-14a01692-f193-4f78-9d59-90b427646029.png">

<img width="551" alt="Screenshot 2022-12-26 at 6 32 20 PM" src="https://user-images.githubusercontent.com/116780283/209532367-7ca41bdc-f3f3-43b1-89e1-c3ffc8e7b93d.png">
<img width="458" alt="Screenshot 2022-12-26 at 6 33 17 PM" src="https://user-images.githubusercontent.com/116780283/209532423-50e9de98-3bd6-4ae0-a8c7-36f040645c17.png">

Currently I followed your instructions
1. open terminal on MAC. (I use MAC) 
2. Navigate to Blender: cd /Applications/Blender/Contents/MacOS
    Run Blender as admin: sudo ./Blender
3. but as you can see the above, file can not be found. 
4. so I installed and clicked the install dependencies
5. and turn off the computer to make sure it install safely. 
6. then as you can see the above, still keep telling me to install dependencies. 

please help me what to do. 

Thank you heaps

**Comment by cgtinker** [comment]
Hey there, 

I've finally had the chance to test on a silicon mac. 
If you are using a silicon mac:
- download the zip from the main branch, not the release version
- try installing the dependencies
- if access gets denied navigate to `System Settings > Privacy and Security > Full Disk Access` then activate your Terminal. After doing so, sudo shouldn't be required anymore. Run Blender: `./Blender`

**Comment by cgtinker** [comment]
if you still have issues, please refer to #130
