### ISSUE TITLE
Warped/streched face output

### ISSUE THREAD

**Issue by Qwumpus** [cgtinker/BlendArMocap#114]
![image](https://user-images.githubusercontent.com/77427880/210120444-3d68c251-03c2-4699-8d6e-1dfdf6865212.png)

I am using the correct video format and resolution, but my face is warped and distorted, leading to strange results when I apply the animation.

**Comment by cgtinker** [comment]
Sorry for the late response - to be honest this results look like the result you would get from mediapipe. guess it's a mapping issue. I've been working on an major rework of the transfer and just pushed it to the main. You might want to give it a go - it still requires some testing before I can call it an official release but it's worth to give it a shot!
