### ISSUE TITLE
when I hit button "transfer annimation", nothing happened

### ISSUE THREAD

**Issue by dustturtle** [cgtinker/BlendArMocap#115]
anybody help?
no error, but nothing happened.

only logging in terminal :
TRYING TO TRANSFER ANIMATION DATA FROM cgt_POSE TO rig

mac OS 12.4, blender 3.4.1

**Comment by cgtinker** [comment]
do you have a generated rigify rig as target?
is a cgt_collection selected?

besides, huge update is on the way - rewrote the entire transfer and added lots of features across the board. it's available at the main branch atm, will officially release it as soon I'm done with testing - might be worth a try already ;)

**Comment by cgtinker** [comment]
> do you have a generated rigify rig as target? is a cgt_collection selected?
> 
> besides, huge update is on the way - rewrote the entire transfer and added lots of features across the board. it's available at the main branch atm, will officially release it as soon I'm done with testing - might be worth a try already ;)

@dustturtle did you try the new version from the main branch? does the error persist?
