### ISSUE TITLE
 There is no install button in the add-on's menu.

### ISSUE THREAD

**Issue by fnami86** [cgtinker/BlendArMocap#117]
OS : win10
Blender : 3.3.3.0 LTS

I run Blender as administrator and installed the addon, but I can't install Mediapipe because the button doesn't appear. Am I doing it wrong? It is a very useful addon and I would like to use it.

**Comment by cgtinker** [comment]
what's the add-on version?

**Comment by fnami86** [comment]
thanks.
addon 1.6.0
I also tried 1.5.2.The install dependencies button is displayed, but only cv2 becomes True when executed. google.protobuf & mediapipe is False.

**Comment by cgtinker** [comment]
can you toggle the system console (v.1.6.0), copy the logs and paste them here please?

**Comment by toastamore** [comment]
Hi @cgtinker ! I would like to report the same problem. I'm not sure if it could be useful, but here my toggle system console

fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Vittoria\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons\\Set_All_Simplify.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Vittoria\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons\\Set_All_Simplify.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Vittoria\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons\\Set_All_Simplify.py'
addon_utils.disable: BlendArMocap-main not disabled
Modules Installed (BlendArMocap-main) from 'C:\\Users\\Vittoria\\Desktop\\BlendArMocap-main.zip' into 'C:\\Users\\Vittoria\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons'
(3, 1, 0) Python Executable: C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\bin\python.EXE.

![image](https://user-images.githubusercontent.com/62658072/214058057-1ce9991d-a2cc-480f-8917-21de868e2305.png)

**Comment by fnami86** [comment]
The system console is as follows.

BlendArMocap-main, C:\Users\y_fuj\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlendArMocap-main\src
(3, 3, 3) Python Executable: C:\Program Files\WindowsApps\BlenderFoundation.Blender3.3LTS_3.3.3.0_x64__ppwjx1n5r4v9t\Blender\3.3\python\bin\python.EXE.
ValueError: the return value must be None
File "C:\Users\y_fuj\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\cats-blender-plugin-master\tools\settings.py", line 249, in update_settings
addon_utils.disable: BlendArMocap-main not loaded
Modules Installed (BlendArMocap-main) from 'C:\\Users\\y_fuj\\Desktop\\BlendArMocap-main.zip' into 'C:\\Users\\y_fuj\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons'
module changed on disk: 'C:\\Users\\y_fuj\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\BlendArMocap-main\\__init__.py' reloading...


![2023-01-24 103035](https://user-images.githubusercontent.com/123343832/214194920-b332e1cb-710c-4748-b86c-0cef07b17ec4.png)

**Comment by cgtinker** [comment]
1. Unzip Blendarmocap
2. Change the name on the unzipped folder to BlendArMocap
3. Zip it again

Let me know if that solves your issue

**Comment by fnami86** [comment]
Thanks for letting me know this far. But I ran into a different problem.
As you instructed, I recreated the zip and the install button appeared!
But installing dependencies fails.
The console message seems to be about the Python version.
---------------------------------------------------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.3.0.0_x64__ppwjx1n5r4v9t\Blender\3.3\python\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.3.0.0_x64__ppwjx1n5r4v9t\Blender\3.3\python\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.3.0.0_x64__ppwjx1n5r4v9t\Blender\3.3\python\lib\site-packages\pip\_internal\commands\install.py", line 446, in run
    self._handle_target_dir(
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.3.0.0_x64__ppwjx1n5r4v9t\Blender\3.3\python\lib\site-packages\pip\_internal\commands\install.py", line 505, in _handle_target_dir
    shutil.move(
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.3.0.0_x64__ppwjx1n5r4v9t\Blender\3.3\python\lib\shutil.py", line 821, in move
    copytree(src, real_dst, copy_function=copy_function,
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.3.0.0_x64__ppwjx1n5r4v9t\Blender\3.3\python\lib\shutil.py", line 556, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.3.0.0_x64__ppwjx1n5r4v9t\Blender\3.3\python\lib\shutil.py", line 457, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.3.0.0_x64__ppwjx1n5r4v9t\Blender\3.3\python\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] アクセスが拒否されました。: 'C:\\Program Files\\WindowsApps\\BlenderFoundation.Blender_3.3.0.0_x64__ppwjx1n5r4v9t\\Blender\\3.3\\python\\absl'
WARNING: You are using pip version 21.2.4; however, version 22.3.1 is available.
You should consider upgrading via the 'C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.3.0.0_x64__ppwjx1n5r4v9t\Blender\3.3\python\bin\python.EXE -m pip install --upgrade pip' command.
Error: Installation of opencv_contrib_python failed. Check system console output.
Error: Installation of protobuf failed. Check system console output.
Error: Installation of mediapipe failed. Check system console output.

**Comment by cgtinker** [comment]
Did you start blender as admin? 

EnviromentErrors are usually based on one of those two reason:
- You don't have the necessary privileges to access a path. Admin rights should fix it 90% of the time.
- A file gets deleted which is currently in use by the application. Usually a restart should do

Not really sure what's the best way of handling that. I could add a '--user' tag to the commands and link the local python site packages to blender. But it seems bad practice. Requiring elevated privileges seems also bad...

**Comment by cgtinker** [comment]
the button issue is fixed, if dependency issues arise please refer to the topics I've created for them

**Comment by Kazeem6511** [comment]
Please how can I install blendarmocap dependency all other is true except mediapipe please I need your help.

**Comment by marcopolo5555** [comment]
To everyone who installed this add-on and struggling to install mediapipe-silicon directly in the add-on, here is the solution. the latest version of this add-on is 1.6.1, it was released in 2023. In this time the version of media pipe-silicon 0.9.2.1 was released. Unzip the add-on, go to cgt_dependencies.py find "mediapipe-silicon" change the version from 0.8.11 to 0.9.2.1. Delete old add-on installation in blender install the new one with changed 0.9.2.1 version and it should work.
