### ISSUE TITLE
Blender3.4 when install BlendArMocap-1.5.2 show error msg ModuleNotFoundError: No module named 'BlendArMocap-1'

### ISSUE THREAD

**Issue by zhuziying** [cgtinker/BlendArMocap#122]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'BlendArMocap-1'
What's the matter？

**Comment by cgtinker** [comment]
Can you give me a description how to reproduce the issue?
Did you maybe activate the add-on, then deleted the add-on directory or changed to path to it while it's registered in Blender?

**Comment by zhuziying** [comment]
i use BlendArMocap-freemocap is fine,but BlendArMocap-1.5.2 is show No module named 'BlendArMocap-1'  
![image](https://user-images.githubusercontent.com/4710245/219949974-8b5e12e0-8c68-4710-8de8-f09771f933f1.png)
after install BlendArMocap-1.5.2 ,when i active the add-on then error show
![image](https://user-images.githubusercontent.com/4710245/219950083-ec98503a-2fde-4b74-982c-32c96523844f.png)

**Comment by zhuziying** [comment]
maybe i download error version, the release version is fine .thank you very much, u are warm hearted.
