### ISSUE TITLE
the result seems not right

### ISSUE THREAD

**Issue by jinfagang** [cgtinker/BlendArMocap#125]
![2023-02-21-20-56-57 00_00_00-00_00_30](https://user-images.githubusercontent.com/21303438/220350958-ab5f3a0c-e738-4500-8118-9246647f8d6e.gif)

this look abornal

**Comment by cgtinker** [comment]
At the first glance, it looks like your key step is way off.
Did you import a video or used the webcam?

Not really sure what's going on with the hips. 
Legs are hard to get right, usually require pretty good video material otherwise it's better to not transfer to the legs.

**Comment by jinfagang** [comment]
@cgtinker this is my test video, would u help me verify on your model to see if generated rotations are normal?


https://user-images.githubusercontent.com/21303438/220503800-b87e83de-0e1c-41ba-94b8-543c0ea75caf.mp4

**Comment by cgtinker** [comment]
I think you have used a key step of 4 when importing the video. The heavy rotations are mostly spikes of the detection. Found that there's wrong constraint on the shoulders, however - try the following:

- choose a key step of 1, then import the video
- after importing, select all objects from the collection `cgt_Drivers > cgt_Pose`
    - make sure one of those objects is actually active
- navigate to `object constraint properties > blendarmocap > tools`
    - Press the `Smooth animation data of selection` button to reduce the jitter
- Select the object `cgt_shoulder_center`, navigate to  `object constraint properties > blendarmocap`
    - change the` copy rotation constraint > mix` mode to `add`
    - press the `tools > transfer selection` button

**Comment by jinfagang** [comment]
@cgtinker thank u. what does key step means here, how does it effect result?

**Comment by cgtinker** [comment]
basically you skip 3 frames, just 1 of 4 gets applied. It's faster, reduces jitter but if you have unlucky frames it can lead to spikes - [docs](https://cgtinker.github.io/BlendArMocap/detection.html). In the future I consider to apply auto smoothing based on the skipped frame.

**Comment by cgtinker** [comment]
> @cgtinker thank u. what does key step means here, how does it effect result?

Added the auto smoothing based on the skipped frames now.
 - Key Step of 1 = No smoothing
 - The higher the keystep, the more smoothing

Also fixed some driver / constraint issues. 
Try pulling from the main, use a keystep of ~3
Should produce way better results now
