### ISSUE TITLE
Able to export fbx

### ISSUE THREAD

**Issue by Arex360** [cgtinker/BlendArMocap#136]
It would be better, if we able to export animation as well, or is there any way? I can bake the animation?

**Comment by KaijuKoder** [comment]
Suggested workflow: You can bake the animation in Blender using Pose -> Animation -> Bake (Visual Keying = Yes), either for the whole sequence, or single frames of your major keyframes. To see what the baked animation looks like you need to disable or remove the constraints. Once you're happy, you can delete the constraints or if you just want an FBX export that (I think).

**Comment by cgtinker** [comment]
Did KaijuKoders comment fix your issue?

If you plan to export to game engines you may want to try my add-on [rigify gamerig extension](https://github.com/cgtinker/rigify_gamerig_extension).

**Comment by Arex360** [comment]
The extension didn't work ( was not able to install in blender 3.4)

**Comment by KaijuKoder** [comment]
@Arex360, you are probably trying to install the old version in https://github.com/cgtinker/rigify_gamerig_extension/releases. Try downloading the latest version: https://github.com/cgtinker/rigify_gamerig_extension -> [Code] -> Download ZIP. Just checked and it works for me under Blender 3.4.

**Comment by Arex360** [comment]
After cloning rigify_gamerig_extension, I am able to bake but it only bake 1 pose only, I want to bake all poses and export the animation

**Comment by cgtinker** [comment]
> After cloning rigify_gamerig_extension, I am able to bake but it only bake 1 pose (frame)only, I want to bake all poses(frame) and export the animation

I'll fix the issue add-on installation issue soon. Mainly a naming thing. U should be able to use the bake function in the add-on multiple times. The anims should be stashed as NLA tracks and therefore be exportable. Did you bake the animation? (Select the generated rig and bake in the extension panel)

**Comment by cgtinker** [comment]
closing this as it is not a blendarmocap issue, everything can be done within blender therefore it's a issue facing blender
