### ISSUE TITLE
Problem with metarig 

### ISSUE THREAD

**Issue by Desagiato** [cgtinker/BlendArMocap#139]
If I try to transfer the animation to the rig, it works, but if I try to transfer it to the metarig it doesn't work, why? How can I fix it?
![Schermata del 2023-03-03 00-00-13](https://user-images.githubusercontent.com/114653399/222579554-6f46056a-d9f8-4657-949d-8e6f92586d84.png)
![Schermata del 2023-03-02 23-57-18](https://user-images.githubusercontent.com/114653399/222579586-47836da4-6684-4d5a-beaa-13098dc68de6.png)

**Comment by cgtinker** [comment]
For animation within blender you may want to stick to the generated rig as it delivers more control. If it's just a visibility issue you can activate `bone layer 28` and set the rigs `viewport visibility` to `solid`.
If you plan to export to game engines or similar and want to use a metarig to do so you can use my [rigify gamerig extension](https://github.com/cgtinker/rigify_gamerig_extension) so you can easily transfer from the generated to the metarig.
