### ISSUE TITLE
I can't install the addon, and I keep getting this popup that I don't understand. Question about using Holistic and tracking.

### ISSUE THREAD

**Issue by beginner3D** [cgtinker/BlendArMocap#140]
Trying to use the newest version and every time I try to click the checkbox, I get this error.

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'BlendArMocap-1'

**Comment by beginner3D** [comment]
After redownloading the zip folder from Github and deleting the first downloaded zip folder, it worked.

**Comment by beginner3D** [comment]
I was wondering when will the Holistic movements pose animations be unmirrored or flipped (Left- and right-hand movements)? Also, can this addon detect complex fast-moving hand movements in videos, or only slow-moving hand movements?

**Comment by cgtinker** [comment]
1. It's actually not mirrored? Compare the imported video and the results.
Names, and the visual clip are mirrored to reflect the underlying data (Mediapipe naming conventions)
2. You can try, should do. If you record with tons of motion blur it won't work - use a high shutter speed and U should be fine.
