### ISSUE TITLE
tries to import pkg_resources but never workds 

### ISSUE THREAD

**Issue by UnBeatWaterGH** [cgtinker/BlendArMocap#145]
**Describe the bug**
A clear and concise description of what the bug is. tries to import pkg_resources but never workds 

**To Reproduce**
1. Go to 'Install Debian 11'
2. Click on 'Install Blender 3.4 through Snap'
3. Scroll down to 'Open blender and enable this piece of crap'

**Expected behavior**
A clear and concise description of what you expected to happen. THAT IT LOADS

**Screenshots**
Always copy the log message from the system console if an error occurs. Do not create screenshots of error messages. If applicable, add screenshots to help explain your problem.  

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]Debian 11 Bullseye
 - Blender Version 3.4
 - BlendArMocap Version latest of issue create

**Additional context**
Add any other context about the problem here. Tried manual install but it didn't help to get rid of the error. And goddamn Github is being annoying and moving my scroll down whenever i type it's so anoying

**Comment by UnBeatWaterGH** [comment]
Maybe it's just my sleepless mind being a dumb piece of shit, but usually i am smart even when i havent gotten sleep

**Comment by UnBeatWaterGH** [comment]
just please fix this

**Comment by cgtinker** [comment]
can you try downloading blendarmocap from the main branch as zip?
I just recently recognised this issue and it should be fixed on the main branch already..

system console: on linux you should be able to run blender by just typing './blender' in your terminal. this best way to get your hands on blenders log messages.

opencv likes to cause trouble on linux. best to install it via your package manager 
`$ sudo apt-get install python3-opencv`

**Comment by UnBeatWaterGH** [comment]
> can you try downloading blendarmocap from the main branch as zip?

Sure, once I get outa bed, like I just woke up and tired as hell, so my next reply might take a while.

> system console: on linux you should be able to run blender by just typing './blender' in your terminal. this is best way to get your hands on blenders log messages.

That's what I did lol

**Comment by UnBeatWaterGH** [comment]
> system console: on linux you should be able to run blender by just typing './blender' in your terminal. this is best way to get your hands on blenders log messages.

But it's actually 'snap run blender' since I don't want 2.9 which if I remember correctly is the version in Debian.

**Comment by UnBeatWaterGH** [comment]
@cgtinker Didn't help at all.

**Comment by UnBeatWaterGH** [comment]
Had to use development branch not main.

**Comment by UnBeatWaterGH** [comment]
Also if i use elevated privliges then the addon will be installed for root, and i don't deel that that's pleasant.

**Comment by cgtinker** [comment]
Oh you are right about the branch :/
Yeah I dislike that as well, best way around seems to be an external executable. Startet working on it but takes time..
