### ISSUE TITLE
Support VRM humanoid avatar

### ISSUE THREAD

**Issue by nicobou** [cgtinker/BlendArMocap#154]
**Is your feature request related to a problem? Please describe.**
The VRM file format is dedicated to 3D avatar. https://vrm-consortium.org/en/ 
It can be imported in blender with the following add-on : https://vrm-addon-for-blender.info/en/
Once imported, the avatar is rigged.
This can be tester with the VRoid studio application, that is dedicated to "easy" avatar creation, and export VRM files.  https://vroid.com/en/studio

**Describe the solution you'd like**
As I understand the way BlendArMocap is built, it might be doable writing a custom "transfer" for VRM models

**Describe alternatives you've considered**
An alternative to the feature requested here is to load the VRM avatar into blender, and redo the rig with the Rigify armature.

**Additional context**

**Comment by cgtinker** [comment]
While I understand the request I don't plan to support other rigs. In the future I plan to provide my own "simple" rig which can be used to transfer motion.
