### ISSUE TITLE
Freemocap import

### ISSUE THREAD

**Issue by Andrey3d** [cgtinker/BlendArMocap#158]
Freemocap import doesnt work, video - https://drive.google.com/file/d/1zZR6e8NZ_g3ErD4-nZhlukf-IPA68h87/view?usp=sharing

 - OS: Windows 11
 - Blender 3.3.1 
 - BlendArMocap Version 1.6.0

**Comment by cgtinker** [comment]
there has been a pathing issue, fixed it and created a new release.
make sure to select a freemocap directory path containing output data.
