### ISSUE TITLE
Left and Right hands are swapped

### ISSUE THREAD

**Issue by steven850** [cgtinker/BlendArMocap#18]
Was just trying out this add on to do some hand tracking and its very impressive, the problem ive run into is that the left and right hands are swapped. So my left hand ends up on the characters right hand, this causes some serious glitches as I have rotation limits in place, and the hand is trying to rotate in the wrong direction. Any idea how to fix this?

Thanks,
Steven

**Comment by cgtinker** [comment]
Hey Steven,

are you using BlendArMocap version 1.2.0?
I've updated the add-on a few days ago (flipping issues should be fixed).
You can get it from the main branch or gumroad.

Soon I'll revisit the hand tracking results, so let me know if there are any issues in the current version.

**Comment by steven850** [comment]
Ahh ok. I didnt see there was a new version, my mistake. Seems to be on the correct side with this version, however, I cant select my rig after having installed the new version. So before I could select the rig "genesis 8.1" and transfer the motion. Now if I open the character file fresh and try to do it I can only select "rig" and that doesnt work. It doesnt show the "genesis 8.1".

**Comment by steven850** [comment]
![SC1](https://user-images.githubusercontent.com/43098060/154731460-0a5586aa-3728-4de9-8a39-a6ee89101d36.PNG)
![SC 2](https://user-images.githubusercontent.com/43098060/154731466-1488aae7-2542-4a3e-8468-89ab6752f8b8.PNG)

**Comment by cgtinker** [comment]
IActually I didn't change the selection functionality, prolly it searches for the same name (bonegroup / rig name) - could you confirm that by changing your armature name to "rig"?

I'll fix that soon.

**Comment by steven850** [comment]
That seems to work. How did you design the hand capture to work, should I be recording top down? Or POV from the head?  Just having the cam on the desk doesn't yield very good results.

**Comment by cgtinker** [comment]
Thanks, good to know.
Hand tracking works best when your palms are facing the camera. Currently only the x-angles are getting transferred so basically it focusses on opening and closing the hand. As the pose tracking shall transfer the hand orientation properly in the future, the current plan is to only record the fingers and the hand up and down rotation. I'm planning to transfer the y-angles swell soon. 
I've just started reworking some of the mapping so the fingers start stretched, not already with a base angle, will be up soon ;)

**Comment by steven850** [comment]
ahh ok. 
Nice
Does tracking accuracy improve with markers or does it ignore them and just focus on edges?

**Comment by cgtinker** [comment]
Nope it focuses on the edges. I'll improve the quality soonish, working on an update ;)
