### ISSUE TITLE
Hands are angled weirdly

### ISSUE THREAD

**Issue by MrColz** [cgtinker/BlendArMocap#19]
Hello!

When applying captured hand movements, the hands never seem to be angled properly and always turning in unnatural ways. Is there any position I need to put my hand in so they stay straight forward instead of straight up or to the side?
Example:
![aaaaaaaaaaaaaaaaaa3](https://user-images.githubusercontent.com/100011500/154826222-783a480e-adbd-426f-8360-df072f87d302.png)

**Comment by sunhaha123** [comment]
also want to know ..

**Comment by cgtinker** [comment]
Will be fixed in the upcoming release version
