### ISSUE TITLE
Video import

### ISSUE THREAD

**Issue by cgtinker** [cgtinker/BlendArMocap#2]
//

**Comment by Jbaal** [comment]
Yes! Thank you! Last week I tried blendartrack for face detection, I was so happy to find an easy solution that offers to adapt all thoses mediapipe datas to a rigify armature in Blender. And today I discover your new plugin with even more joy! I'm actually making a music video with 0 budget in Blender, I wanted to use mocap but couldn't find a "cheap"/free tool for it, so thank you with all my heart!
So, yes, to come back to the subject, a video import would be really useful!

**Comment by cgtinker** [comment]
Thanks, glad you like it :)

Face tracking results are better with blendartrack at the moment as I am focusing more on pose and hand tracking data for now.

Google announced some updates for face detection which will enable me to deliver the same results with blendarmocap in the future.

Guess the next major update will include video tracking and lots of tweaks.

**Comment by Jbaal** [comment]
Cool! I'm gonna try the actual version of BlendArMocap right now, and if it fits my needs (and I'm pretty sure it will!) I won't forget to make a donation (do you have a paypal open for donations? so I'm sure you'll have 100% of it) and make refererences of your work when I'll release the music video.

**Comment by qfb594** [comment]
why?
Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-main\cgt_blender\interface\stream_detection_operator.py", line 40, in execute
    self.init_detector(detection_type)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-main\cgt_blender\interface\stream_detection_operator.py", line 60, in init_detector
    self.tracking_handler.stream = stream.Webcam(camera_index=camera_index)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-main\cgt_utils\stream.py", line 16, in __init__
    raise IOError("Cannot open webcam")
OSError: Cannot open webcam

location: <unknown location>:-1

**Comment by cgtinker** [comment]
Video import will be supported in the upcoming update.
