### ISSUE TITLE
A combined mode that tracks everything at the same time

### ISSUE THREAD

**Issue by TiagoTiago** [cgtinker/BlendArMocap#20]
Would that be possible with just one camera?

**Comment by cgtinker** [comment]
Possible, but sadly way to slow - probably running with just about a frame per second.

**Comment by TiagoTiago** [comment]
> Possible, but sadly way to slow - probably running with just about a frame per second.

The current tracking doesn't seem to be running at just 3 frames per second. Where would all that extra overhead come from?

And wouldn't that be highly dependent on the hardware it's running on?
