### ISSUE TITLE
No module named error 

### ISSUE THREAD

**Issue by kapilmathur123** [cgtinker/BlendArMocap#22]
![error](https://user-images.githubusercontent.com/64973118/155335094-0a8fca63-9f56-40a8-b5ec-b812831eba1b.png)

got this error when I press "install dependencies" in blender preferences

**Comment by cgtinker** [comment]
can you link the console text?
the installation process failed in your case.

**Comment by kapilmathur123** [comment]
![error](https://user-images.githubusercontent.com/64973118/155886382-aaf953aa-95bd-4060-9d7d-da45f20028cf.png)
![error1](https://user-images.githubusercontent.com/64973118/155886385-74c66f56-2d19-47af-948b-c4176755fb29.png)

**Comment by cgtinker** [comment]
in the screenshot it looks like it has been installed on your system python. On windows users can have a custom python environment path in blender which may causes this issue. 
For now, just copy the folders mediapipe, mediapipe-0.8.x.x.dist-info, cv2, opencv_contrib_python-4.x.x.xx.dist-info, opencv_python-4.x.x.xx.dist-info from your site packages in blenders site packages.

you should find the folders at:
User/username/AppData/Roaming/Python/Python39/site-packages
and move the folders to (path may differ a bit):
.Blender/Contents/Resources/3.0/python/lib/python3.7/site-packages

**Comment by kapilmathur123** [comment]
i got this location User/username/AppData/Roaming/Python/Python39/site-packages but i did not got this location Blender/Contents/Resources/3.0/python/lib/python3.7/site-packages

can you share this Blender/Contents/Resources/3.0/python/lib/python3.7/site-packages location screenshot

**Comment by kapilmathur123** [comment]
![error](https://user-images.githubusercontent.com/64973118/156004496-f46d3922-cd6e-405c-bdc7-fea6bdb89c30.png)
no module named " google" error

**Comment by kapilmathur123** [comment]
![error](https://user-images.githubusercontent.com/64973118/156102303-9e07c20b-7e60-4b15-a9a0-5be2e2bf5b7c.png)
no its not work

**Comment by kapilmathur123** [comment]
and I also want to suggest you that you should make software or application for this addon for example blendartrack
