### ISSUE TITLE
dependencies greyed out

### ISSUE THREAD

**Issue by vogues** [cgtinker/BlendArMocap#28]
I've run on win 11 steam version via admin elevation- unable to install dependencies. It is not clickable.
v3.1

**Comment by cgtinker** [comment]
when the dependencies are greyed out, they should be installed. did you try running the add-on?
Also I didn't test on 3.1 - so far 2.9 & 3.0 are (officially) supported

**Comment by vogues** [comment]
oh i see, the addon is in the panel- i just assumed the dependencies didnt install and so it wouldnt work. ill test when i get my webcam going.
