### ISSUE TITLE
dependencies download on Mac M1 

### ISSUE THREAD

**Issue by Rubadel** [cgtinker/BlendArMocap#29]
I have been faced this error

Command '['/Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9', '-m', 'pip', 'install', 'mediapipe', '--user']' returned non-zero exit status 1.

When try to download a mediapipe I had this error

error: could not find a version that satisfies the requirement mediapipe (from versions: none) error: no matching distribution found for mediapipe

Help Plz 😔

**Comment by cgtinker** [comment]
make sure you use the intel version on mac, not the silicon version.
let me know if it helps!

**Comment by Rubadel** [comment]
my MacBook has M1 silicon, how can I use the intel version 🤔, or are you mean that is not working on M1 ?

**Comment by cgtinker** [comment]
when downloading blender from blender.org choose the "intel" and not the "silicon" version.

**Comment by m-ali-awan** [comment]
Can we use this addon at all on silicon versions, ? 
I am unable to do so on my mac m2 pro
