### ISSUE TITLE
Mocap for other rigs in blender

### ISSUE THREAD

**Issue by zhan0502** [cgtinker/BlendArMocap#31]
Great works! Is this also workable to rigs that doesn't have IK drivers? E.g. If I create a generic character in blender, can I still use this to rotate the bones? 
Thanks.

**Comment by cgtinker** [comment]
So far, there is no support for doing so. I'm planning to introduce workarounds in the future. To archive this in blender I'd suggest you the following:
1. transform the rigify rig so it matches the proportions of your character.
2. generate the rig, and animate it
3. make sure to turn off stretching bones
4. bake the animation, make sure to include drivers
5. the baked animation should yield the rotations which you can use for a custom transfer

**Comment by cgtinker** [comment]
Will be supported in the upcoming version, check:
#35
