### ISSUE TITLE
Cant install dependencies on addon even after updating python 

### ISSUE THREAD

**Issue by Noiet** [cgtinker/BlendArMocap#34]
Soo yeah, ive done every step correctly, opened up blender with privileges and tried to install the dependencies, but whenever i tried to, it always ended up bugging and leaving this message for me

Command '['C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\bin\python.EXE', '-m', 'pip', 'install', 'mediapipe', '--user']' returned non-zero exit status 1.

[https://cdn.discordapp.com/attachments/869803787785736222/959992551958519848/unknown.png](And this message on the console)

I'm not sure whats happening, i tried to restart my pc, update python, run legacy versions, but none of them worked. What could be happening?

**Comment by cgtinker** [comment]
your discord app infiltrated blender? now that's something new 😄 
do you have a vpn running? if so probably turn it down.

there has been an error when processing the cmd. I'm a bit wondering about the path, think there should be double slashes. besides the path and cmd seems fine.
for reference, which operating system and python version are you using?

when updating python / pip, it's sometimes required to restart blender and try the installation a second time (not sure why that happens).

if that doesn't work, a workaround also can be to use the scripting editor in blender and use this short script - might it works:
```
import pip
pip.main(['install', 'mediapipe', '--user'])
pip.main(['install', 'opencv-python', '--user'])
```

**Comment by Noiet** [comment]
Nah, i dont use VPns

I'm using windows and my current version of python is 3.10.4, i tried to that restart and reinstall thing but it didnt work

How do i add that workaround? I tried to drop it in the console here and it didnt work

**Comment by cgtinker** [comment]
Bummer it doesn't run. Not really sure what's the issue - would be nice to see the logs when the python version gets searched to further investigate it.

However, when you open blender there is a tab called "scripting" (usually the last workspace). There you can click on the "new" button - there you can copy-paste the script. To execute it either press the play button or "alt+p"

**Comment by Noiet** [comment]
I tried running it here but i got the [following message](https://cdn.discordapp.com/attachments/386479015747256331/960392569920061470/unknown.png)
Also, downgraded python to 2.7.3, didnt work

**Comment by cgtinker** [comment]
You accidentally have added a '[' to the script. - that's why it doesn't run. 

When talking about python version, preferably use python 3.7. 
Mediapipe doesn't support 2.7... I've successfully installed it on 3.1, 3.7, 3.9.

**Comment by Noiet** [comment]
I tried downgroading to exactly 3.7 and reinstalled, i got an error that is a bit different but still the same in a way

`REGISTERING BLENDARMOCAP
TRY ACCESS INSTALLED DEPENDENCIES
Dependency(module='mediapipe', package=None, name=None)
REGISTRATION FAILED: MODULE NOT FOUND
[root] DEBUG:   restart_nodes() handler
Looking for GlslTexture
accessing pip installer
pip 19.2.3 from C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\site-packages\pip (python 3.7)
Try to install: mediapipe 1
Collecting mediapipe
  Using cached https://files.pythonhosted.org/packages/10/90/6c9a311027fceb349afd8d1d6716dc386c6fdaa5be00de5ddcfaed82af9b/mediapipe-0.8.9.1-cp37-cp37m-win_amd64.whl
Collecting opencv-contrib-python (from mediapipe)
  Using cached https://files.pythonhosted.org/packages/1c/c0/67ce42700579df6579864760bfa89520154e7f01b1fcbe19bf0a10dfb0de/opencv-contrib-python-4.5.5.64.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\bin\python.EXE' 'C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\eu\AppData\Local\Temp\tmpom4wplce'
       cwd: C:\Users\eu\AppData\Local\Temp\pip-install-0u0jxdro\opencv-contrib-python
  Complete output (20 lines):
  Traceback (most recent call last):
    File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
      main()
    File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\eu\AppData\Local\Temp\pip-build-env-13gk6h5k\overlay\Lib\site-packages\setuptools\build_meta.py", line 178, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "C:\Users\eu\AppData\Local\Temp\pip-build-env-13gk6h5k\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires
      self.run_setup()
    File "C:\Users\eu\AppData\Local\Temp\pip-build-env-13gk6h5k\overlay\Lib\site-packages\setuptools\build_meta.py", line 282, in run_setup
      self).run_setup(setup_script=setup_script)
    File "C:\Users\eu\AppData\Local\Temp\pip-build-env-13gk6h5k\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 503, in <module>
      main()
    File "setup.py", line 36, in main
      python_lib_path = cmaker.CMaker.get_python_library(python_version).replace(
  AttributeError: 'NoneType' object has no attribute 'replace'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\bin\python.EXE' 'C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\eu\AppData\Local\Temp\tmpom4wplce' Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 22.0.4 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
INSTALL USING SUPER USER
Collecting mediapipe
  Using cached https://files.pythonhosted.org/packages/10/90/6c9a311027fceb349afd8d1d6716dc386c6fdaa5be00de5ddcfaed82af9b/mediapipe-0.8.9.1-cp37-cp37m-win_amd64.whl
Collecting opencv-contrib-python (from mediapipe)
  Using cached https://files.pythonhosted.org/packages/1c/c0/67ce42700579df6579864760bfa89520154e7f01b1fcbe19bf0a10dfb0de/opencv-contrib-python-4.5.5.64.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\bin\python.EXE' 'C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\eu\AppData\Local\Temp\tmpszcszb0e'
       cwd: C:\Users\eu\AppData\Local\Temp\pip-install-ul71awbj\opencv-contrib-python
  Complete output (20 lines):
  Traceback (most recent call last):
    File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
      main()
    File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\eu\AppData\Local\Temp\pip-build-env-3w3axrya\overlay\Lib\site-packages\setuptools\build_meta.py", line 178, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "C:\Users\eu\AppData\Local\Temp\pip-build-env-3w3axrya\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires
      self.run_setup()
    File "C:\Users\eu\AppData\Local\Temp\pip-build-env-3w3axrya\overlay\Lib\site-packages\setuptools\build_meta.py", line 282, in run_setup
      self).run_setup(setup_script=setup_script)
    File "C:\Users\eu\AppData\Local\Temp\pip-build-env-3w3axrya\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 503, in <module>
      main()
    File "setup.py", line 36, in main
      python_lib_path = cmaker.CMaker.get_python_library(python_version).replace(
  AttributeError: 'NoneType' object has no attribute 'replace'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\bin\python.EXE' 'C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\eu\AppData\Local\Temp\tmpszcszb0e' Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 22.0.4 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`



[Also, i tried to run the code again but it still didnt work  ](https://imgur.com/a/Pqyj5ww)

**Comment by cgtinker** [comment]
the good thing is that the wheel for setting up mediapipe was found, sadly it doesn't spin. I'm never had this issue so I can just guess:

_You should consider upgrading via the 'python -m pip install --upgrade pip' command_, so lets try that. Not sure if it makes any difference but I'd try to install the packages using the terminal:

**ensure pip**
`C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\bin\python.EXE -m ensurepip`
**upgrade pip**
`C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\bin\python.EXE -m pip install --upgrade pip`
**install open-cv**
`C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\bin\python.EXE -m pip install opencv-python`
**install mediapipe**
`C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\bin\python.EXE -m pip install mediapipe`


In this case I'd probably also consider to clear the CMake cache. Sadly no idea about the path..
`rm CMakeCache.txt`

Try that before going further, there is an issue building the whl so it probably should be reported to [mediapipe](https://github.com/google/mediapipe).

**Comment by Noiet** [comment]
I Did all of that except the last one (The Rm CMakeCache one) but it still didnt work, its giving me the same bug

**Comment by Noiet** [comment]
UPDATE: I reinstalled everything from blender and it seemingly started working here
