### ISSUE TITLE
Unable to transfer animation

### ISSUE THREAD

**Issue by JanLederer** [cgtinker/BlendArMocap#38]
First of all, thanks for developing such great things,
I am playing around with the ArMocap and the Blendtrack 2.0 since a few days 
and I couldn't really archive my first success with it but maybe reporting what 
I get to see on my end might hopefully help you improving it.
I love the stuff you do so far and I hope it will get even better.

As written above my issue is to transfer the captured movement onto generated into a Rigify-Rig 
(made from a a standard blender human rig)
I'm using a mac, running blender 3.0.0 (also tried other versions, elder and younger) but I always 
get the same error (below) leading to no movement in the rig.

This is the error message, hope you have an Idea to solve this:

Error: Python: Traceback (most recent call last):
  File "/Users/XYZ/Library/Application Support/Blender/3.0/scripts/addons/BlendArMocap-release/src/cgt_blender/interface/ui_panels.py", line 92, in execute
    input_manager.transfer_animation()
  File "/Users/XYZ/Library/Application Support/Blender/3.0/scripts/addons/BlendArMocap-release/src/cgt_blender/input_manager.py", line 19, in transfer_animation
    selected_armature = user.selected_rig.name_full
AttributeError: 'NoneType' object has no attribute 'name_full'

location: <unknown location>:-1

**Comment by cgtinker** [comment]
did you actually select the rig? 

to transfer the data you got to select a collection containing drivers and a generated rigify rig in the add-ons panel.

**Comment by JanLederer** [comment]
You are absolutely right, I just tried again with a selected rig and that works. My bad.
Thanks again for the great job you are doing there. I really appreciate it a lot.
