### ISSUE TITLE
KeyError: lip.T for Face as well as pose

### ISSUE THREAD

**Issue by sprites20** [cgtinker/BlendArMocap#40]
The Bone or Joint exists within the Blender Workspace but it's not able to transfer animation of the Face and Pose due to KeyErrors
![image](https://user-images.githubusercontent.com/49236696/163919809-832d3622-3b76-4355-b633-d8e3d8357b92.png)
Same error for pose

**Comment by GeoGo12** [comment]
Getting the same error

![Blender 4_28_2022 10_58_20 AM (2)](https://user-images.githubusercontent.com/104584921/165798997-65a95999-9ed4-4a12-84ca-93ded8c11824.png)
