### ISSUE TITLE
Crash! when I press "start detection" blender will crash. my system is Mac osx my device is MacBook Pro 2021 m1 max

### ISSUE THREAD

**Issue by hondo666** [cgtinker/BlendArMocap#41]

**Comment by cgtinker** [comment]
1. Are you using the Intel version of blender? (Mediapipe doesn't run on the silicone blender version)
2. Are you starting blender as admin? Required on Mac OS.

**Comment by hondo666** [comment]
I have solved it out ! I have tried to use  arm version of blender and Intel version of blender. In the end I found I only could use Intel version of blender to install BlendArMocap. If I use Intel version of blender ,it will show"Command '['/Applications/Blender.app/Contents/Resources/2.93/python/bin/python3.9', '-m', 'pip', 'install', 'mediapipe', '-user']' returned non-zero exit status 1." everytime. And about crash,I found out that i have to as admin to open blender everytime.  I can't just as admin to install in that once.

**Comment by hondo666** [comment]
thank you !

**Comment by cgtinker** [comment]
glad you figured it out!
sadly mac-os is kinda restrictive on using the camera and I couldn't figure out a way how to give blender camera permissions easily... so it always has to be started as admin.

**Comment by TheChesireCat** [comment]
Hey guys, I am pleased to inform you that thanks to [cansik](https://github.com/cansik) we now have [prebuilt binaries for mediapipe-sillicon](https://github.com/google/mediapipe/issues/3277), this would require you to do custom dependency handling for macos in `dependency.py`. I hardcoded the dependency as `mediapipe-silicon` in the relevant files and repackaged the dependency for quick fix.
