### ISSUE TITLE
Error on camera

### ISSUE THREAD

**Issue by Vordlex** [cgtinker/BlendArMocap#42]
I don't have a webcam so I'm trying to use Droidcam + OBS instead of it to use my cell phone camera, however the video is getting like this, and if I try to choose another webcam besides number 0 and 1 it says it didn't find it. I installed all packages and it didn't returns me any error.

(Windows 11)
![image](https://user-images.githubusercontent.com/43836184/167171423-580addad-2fc6-4e53-adc8-64fc11ecf63e.png)

**Comment by cgtinker** [comment]
Have heard that people used obs successfully. In your case I guess there is an issue wether with droid cam or obs. In the upcoming update video imports will be supported. Refer to the development version for now.
