### ISSUE TITLE
In fullsize pose capture, root should be at feet

### ISSUE THREAD

**Issue by j2l** [cgtinker/BlendArMocap#47]
In pose capture, when I balance arms left and right, the whole body is seen as rotating around Y axis.
Even after zeroing hip center rotation, hip left and right Z locations, feet rotate around Y axis.
Here I had my 2 feet on the ground, only my hands are on the left:
![image](https://user-images.githubusercontent.com/65325/170517021-30549678-f757-46ac-bd7c-94780e911774.png)
selected are 3 hips curves (center Y rotation, Z locations for the 2 others) and you can see they are zero.
I don't know mediapipe and in the capture, I was not rotating on screen. 

Is there a way to set root to feet for us non-dancers? 😄

**Comment by cgtinker** [comment]
Hey there, it's been a while but.. finally - yes!
I changed a lot regarding the transfer, there's now a 'pose_location' empty, which basically does what you want :)

**Comment by j2l** [comment]
Cool, thanks @cgtinker
