### ISSUE TITLE
Unable to transfer animation

### ISSUE THREAD

**Issue by pandana003** [cgtinker/BlendArMocap#5]
There may be something strange because of the translated English, Sorry.
I can capture the motion, but when I press "Start Transfer", the following message appears and it doesn't move.
![スクリーンショット 2022-02-01 165021](https://user-images.githubusercontent.com/58805620/151932121-3d39ff97-487f-49a0-9fb1-3b2f5c64a4d9.png)

What should I do?

**Comment by cgtinker** [comment]
Download and setup the add-on again, there was an issue in the file I've released yesterday.
Should be fixed now.
