### ISSUE TITLE
Blender 3.1 Phyton 3.10.2 No Mediapipe found

### ISSUE THREAD

**Issue by damartd** [cgtinker/BlendArMocap#51]
Blender 3.1 Phyton 3.10.2 No Mediapipe found

**Comment by cgtinker** [comment]
Which operating system are you using?

**Comment by AvasavA** [comment]
i am having the same problem sir i am running windows 11 blender 3.2
No module named 'mediapipe.python' this is the error
do you know how to download every thing manually if even posble

**Comment by AvasavA** [comment]
Thanks for the reply i did use the v1.5.0 and all working great but the eye brows but i think it's more from my hardware

**Comment by cgtinker** [comment]
great, thanks for the reply! are the eyebrows not animated at all or just with low movement? I've added custom properties to increase and decrease mapping results, so maybe u can adjust it :)
added some details in the readme, will make a tutorial about this soon
