### ISSUE TITLE
attributeError: 'NoneType' object ha no attribute 'name_full' 

### ISSUE THREAD

**Issue by griseldarosario** [cgtinker/BlendArMocap#58]
Hi! 

When I'm trying to use the function in the button called "Transfer Animation" it gives me an Error saying attributeError: 'NoneType' object ha no attribute 'name_full'. Prevously I used the functio in the button called "Start Detetion" and this function works well, the error is when I trr to use the button "Transfer Animation". I hope you can help me, thanks

![image](https://user-images.githubusercontent.com/42854944/172482659-af58f149-7c6f-4c92-bb72-c296b38c3853.png)

**Comment by cgtinker** [comment]
Well U pressed the transfer button but neither selected what to transfer nor where to transfer to.

The transfer target should be a generated rigify rig. Armature > metarig / rigify > generate rig

The collection to transfer should be b.e. the cgt_hands/ pose/ or face collection.

May check the readme or some tutorial on my YouTube to get started. :)
