### ISSUE TITLE
OSError: Cannot open webcam

### ISSUE THREAD

**Issue by HWT-WalterHu** [cgtinker/BlendArMocap#60]
When I tried to use Movie mode and selected a mp4 video from somewhere, it raised OSError: Cannot open webcam.

After some debugging, I finally found that the real problem was the relative path cannot be found, as the following lines from the debug infos:
<img width="873" alt="image" src="https://user-images.githubusercontent.com/23095158/172849657-2beab263-f96f-49c8-b91c-7309d6f7a8f5.png">

The easiest way to fix it is just manually typing the absolute path in Blender window, as the following picture
![image](https://user-images.githubusercontent.com/23095158/172850816-5f383488-5aad-413c-b893-25c28916b0cf.png)

but hope it would be fixed in the future

**Comment by HWT-WalterHu** [comment]
> 

I was using a Mac OS

**Comment by cgtinker** [comment]
I've started to implement a fix, could u try the version from the development branch?

**Comment by HWT-WalterHu** [comment]
Thanks for your work!
I replaced the release files with the developments files. It works well for me!

BTW, is there a better way to modify codes of an installed Blender addon, than to cover the original file and restart Blender over and over again? (If it's easy to tell)

**Comment by cgtinker** [comment]
Well it depends on the add-ons setup itself. There is a blender icon (top left) then
'press > system > reload scripts'

However this functionality is often not implemented by add-on devs. I personally use it (mainly on MacOS) and sometimes disable it. So it might can be used but so far it isn't reliable. Tbh I am not sure why it sometimes doesn't reload properly.. 

I plan to implement a 'developer' button in the future. But mainly for myself, not really as a feature.. :p
