### ISSUE TITLE
KeyError: 'bpy_prop_collection[key]: key "lid.T.R.002" not found'

### ISSUE THREAD

**Issue by standingpine00** [cgtinker/BlendArMocap#61]
This error pops up when trying to transfer face capture.  Hands and pose don't have any issues.

**Comment by cgtinker** [comment]
did you use the old rigify face?
the upgraded face rig isn't supported

**Comment by standingpine00** [comment]
I just imported a MakeHuman model and applied the rigify rig to it, so I'm not sure if its the new or old face rig.  That maybe it, I'll take a closer look. Thanks

**Comment by standingpine00** [comment]
Yep, that's the issue.  Thank you so much for the help
