### ISSUE TITLE
Recommendations to reduce jittering?

### ISSUE THREAD

**Issue by ebegu** [cgtinker/BlendArMocap#63]
Hi,

in your readme, you give advice on smoothing the results. But I have to ask: are those wiggly and randomly disappearing markers to be expected or are there some rules to improve the detection so manual corrections are not/less needed?

Currently the raw results of movie tracking (so no key step that I could have set wrongly) look more like someone is getting electric shocks.

**Comment by cgtinker** [comment]
Haha yeah. 
I wanted to have the raw data w/o smoothing available as I personally hate it when I use tools and only get highly processed data.

Applying 'smooth keys' from the graph editor once or twice usually results in decent results - I might implement a button which is easily accessible in the add-ons interface in the future.

**Comment by cgtinker** [comment]
Randomly disappearing markers however, not sure. On one frame or multiple in a row w/o a lot of motion blur / occlusion?

**Comment by ebegu** [comment]
So smoothing generally is a necessary step of the process and not just for rare outliers, that's good to know to manage expectations.

Regarding pose detection:
Especially when the actor stands (mostly still) with just one side facing the camera, all markers are vanishing for longer periods (using 1080p 25fps video input). Also, the arm on the far side of the body is not tracked at all although only the upper arm is occluded and the detection of the partially occluded rear leg is popping in and out.
There are several occasions of the torso folding 180° over the hips down to the feet and of the torso bending sideways more than 90° in itself - both probably the consequence of lost shoulder detection.

The neck seems very stiff and does not follow when the head in the source video is bent down to look at the floor. The left/right movement is mostly there, but no forward/down bending of shoulder/neck/head bones.

Smoothing did reduce the jittering, but it did not fix the other issues. So that is why I'm asking for directions how to film: ideal background, what to wear (preferably tight fitting clothes, I guess), how to light, best camera position etc. - if that would make a difference.

**Comment by j2l** [comment]
I agree for a tutorial on best settings. 
I also don't get non-moving skeleton when I'm standing still in front of the camera.

**Comment by Aurosutru** [comment]
Will try the smoothing you describe in the documentation. Am wondering whether the mediapipe smooth_landmarks and smooth_segmentation commands might be good user-selectable options. https://google.github.io/mediapipe/solutions/pose#smooth_landmarks

**Comment by cgtinker** [comment]
> Will try the smoothing you describe in the documentation. Am wondering whether the mediapipe smooth_landmarks and smooth_segmentation commands might be good user-selectable options. https://google.github.io/mediapipe/solutions/pose#smooth_landmarks

this only applies to their "stream detection" which I'm not using. Currently it's based off image detection. 

However, now there's an import option for freemocaps tracking results. It implements multicam tracking with mediapipe - you can check it out here:
https://freemocap.org
