### ISSUE TITLE
error when transferring animation

### ISSUE THREAD

**Issue by Adriano94** [cgtinker/BlendArMocap#64]
I am using blender 3.2 and every time I try to transfer the animation I made with BlendArMocap, it throws this error 

Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-development\src\cgt_blender\interface\ui_operators.py", line 33, in execute
    input_manager.transfer_animation()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-development\src\cgt_blender\input_manager.py", line 45, in transfer_animation
    col_mapping[col](armature, driver_objects)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-development\src\cgt_blender\cgt_rig\rigify_pose.py", line 144, in __init__
    self.center_points = [m_V.center_point(self.edit_bone_head(v[0]), self.edit_bone_head(v[1]))
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-development\src\cgt_blender\cgt_rig\rigify_pose.py", line 144, in <listcomp>
    self.center_points = [m_V.center_point(self.edit_bone_head(v[0]), self.edit_bone_head(v[1]))
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-development\src\cgt_blender\cgt_rig\abs_rigging.py", line 123, in edit_bone_head
    position = self.armature.data.edit_bones[bone_name].head
KeyError: 'bpy_prop_collection[key]: key "upper_arm_fk.R" not found'

 
What can i do to solve?

**Comment by cgtinker** [comment]
1. Did you generate the rig? A transfer to the meta rig won't work.
2. Which version of Blendarmocap are you using?
3. What's your operating system?

**Comment by Adriano94** [comment]
1. Yes, but i try

> 1. Did you generate the rig? A transfer to the meta rig won't work.
> 2. Which version of Blendarmocap are you using?
> 3. What's your operating system?

1. yes, but I'm using a rig that I made and I'm not able to generate the rig in rigify
2. 1.5.1
3. Windows 10

**Comment by cgtinker** [comment]
> 
> > 1. Did you generate the rig? A transfer to the meta rig won't work.
> > 2. Which version of Blendarmocap are you using?
> > 3. What's your operating system?
> 
> 1. yes, but I'm using a rig that I made and I'm not able to generate the rig in rigify
> 2. 1.5.1
> 3. Windows 10

The transfer is only supported to generated rigify rigs.. metarig w/o updated face and generated

**Comment by Adriano94** [comment]
> > > 1. Did you generate the rig? A transfer to the meta rig won't work.
> > > 2. Which version of Blendarmocap are you using?
> > > 3. What's your operating system?
> > 
> > 
> > 
> > 1. yes, but I'm using a rig that I made and I'm not able to generate the rig in rigify
> > 2. 1.5.1
> > 3. Windows 10
> 
> The transfer is only supported to generated rigify rigs.. metarig w/o updated face and generated

ok I'll try to find some way to transfer the animation from an armature with rigfy to one without, because I'm going to need to use what I already had.

**Comment by cgtinker** [comment]
Good way to go about it: 


Create a metarig, make similar proportion as the rig U want to transfer to. 

Generate it, make some anim, may use the custom props to clean the anim.

The data is just bond with constraints, so U can select constraints, jump to the constraint target via right click and use the same constraint on your rig.

Do not delete the rigify rig before U baked the animation. The drivers depend on the custom probs which are on the control bones.

**Comment by outercloudstudio** [comment]
Hey! I'm receiving this same error message even with the generated meta rig.

**Comment by cgtinker** [comment]
> Hey! I'm receiving this same error message even with the generated meta rig.

hey there, I've wrote a giant update by the time - which should fix this issue. You can download the current version from the main branch (I'll push it to the release branch very soon)
