### ISSUE TITLE
Useful buttons request

### ISSUE THREAD

**Issue by CGI-Fox** [cgtinker/BlendArMocap#67]
This is just an idea; 

-Instead of realtime motion capture would be posible to add buttons to only capture one pose or frame (The actual one), this to only capture especific poses to make a animation with that poses, like the process of making a stop motion animation. 

-Or record the pose per 30 frames or per 1, 2 or 3 seconds.

-Button to start and stop recording, not start recording the animation when we start the detection.

-To smoth the animation (As you said in a post). 

-To only capture selected bones or body parts (Like only head, or only lips, or only arms).

-To have more control when working with a video media, like a player or just select the start frame/second and the end frame/second also the frame rate.

-To calibrate the armature; limits, position, rotation, etc... this can be done with the button to add only one pose, a simple way to do this would just add one pose (You in a T Pose) and offset all the tracking points to the character T Pose.

I know this is not easy (Sorry for my bad english by the way) but I think that this can improve the addon withnout working on the AI.

**Comment by cgtinker** [comment]
Thanks for your input!
I kinda like the idea of calibration as the pose detection sometimes delivers tilted results. So basically shifting/tilting the entire animation.

Making a movie player generates too much overhead, editing a movie file before importing will stay the way to go. However, I could prolly add a keystep, similar to the keystep while stream detection to just capture data on specific frames.

The data is just attached via constraints to the rig, the drivers are separated. So it's possible to just disable constraints on bones to target only specific body parts (like only mouth, arms...)


I've some other features in mind, but it will take time. Current main goal is to get again a stable version which finally makes movie import, holistic tracking and custom data slopes available to the public (the protobuf update by google introduced issues for many people and now I have rifle though their packages to clean them up..)

**Comment by CGI-Fox** [comment]
Also, you can do it like EasyMocap? with diferent syncronized cameras or video inputs?

**Comment by cgtinker** [comment]
> Also, you can do it like EasyMocap? with diferent syncronized cameras or video inputs?

While I kinda like the idea of multiple cameras I think it is currently not useable for average users. It either requires a large studio, multiple cameras and calibration or perfect synching and calibration. (Atm I could only test case two).

The software should remain easy to use and integrating multiple cameras will lead to lots of user errors.

So maybe in the far future when all these issues are bypassable?

**Comment by cgtinker** [comment]
A lot is covered in the upcoming update, I'll make an official release and a tutorial soon.
