### ISSUE TITLE
Video popup won't close

### ISSUE THREAD

**Issue by Jbaal** [cgtinker/BlendArMocap#7]
Install went well, I allready had the dependencies, I don't have a webcam so I used Splitcam to feed a video instead.
"Start Detection" works like a charm, but when I close the window showing mediapipe at work, it automatically reopen.
No more keypoints seems to be written, but I have to save and reopen my blender file to get rid of the video popup.

Windows 10
Blender 3.0.1

**Comment by cgtinker** [comment]
Did you close the window by pressing 'Q' or 'ESC'?
You may have to press 'Q' multiple times to finish the recording.

**Comment by Jbaal** [comment]
Ok my bad... 'Q' one time did the job! Thanks!
