### ISSUE TITLE
Blender 3.2 - "ModuleNotFoundError: No module named 'mediapipe'"

### ISSUE THREAD

**Issue by PHMFG** [cgtinker/BlendArMocap#70]
For some reason this  error occurs when i try to enable the add-on on Blender

Is there any way i can fix it? really wanted to test this add-on for a college project =(

![image](https://user-images.githubusercontent.com/99492818/174902550-d4a5b885-7ae3-46e0-a4d9-ff74d914e2fb.png)

**Comment by CGI-Fox** [comment]
I had the same problem, use Developent mode addon, you can find it on the files.

**Comment by FrancescoCiccone** [comment]
I have the same problem, any solution?

**Comment by CGI-Fox** [comment]
Use Development Version

**Comment by FrancescoCiccone** [comment]
Meaning what? Where can I find it? Would you link it to me?

**Comment by CGI-Fox** [comment]
In code section, find Branch button or Main button to select the development version and dowmload it as ZIP

**Comment by cgtinker** [comment]
> I have the same problem, any solution?

please let me know your operating system.

> In code section, find Branch button or Main button to select the development version and dowmload it as ZIP

don't think that will help :>
I'm working on a standalone executable to reduce dependency issues.

**Comment by cgtinker** [comment]
please refer to #130 from now on
