### ISSUE TITLE
cant move the leg and the hand of the rig

### ISSUE THREAD

**Issue by dororo-ak** [cgtinker/BlendArMocap#73]

**Comment by dororo-ak** [comment]
I'm trying to move hands in the hands mode and the legs in the pose mode :/

**Comment by cgtinker** [comment]
are you selecting the "ik hand" or some random bones?
which version of blendarmocap are you using?

**Comment by dororo-ak** [comment]
We can only select the whole rig right ?
I’m using the latest version of blendermocap i guess, I dowload it a few days ago from githubs
Thanks or yours answering !

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :jeudi 14 juillet 2022 00:40
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [cgtinker/BlendArMocap] cant move the leg and the hand of the rig (Issue #73)


are you selecting the "ik hand" or some random bones?
which version of blendarmocap are you using?

**Comment by cgtinker** [comment]
We can only select the whole rig right ?
No, guess you are in object mode (top left corner in 3d view). Switch to pose mode ;)

**Comment by cgtinker** [comment]
closed due to inactivity
