### ISSUE TITLE
Blender3.0 can't Add-ons BlendArmocap Success.

### ISSUE THREAD

**Issue by elastikukk** [cgtinker/BlendArMocap#79]
it always show me that Requires external packages and elevated privileges. Please help me~~~~
I also type the terminal, but always show that massage 
cd: no such file or directory: /Applications/Blender/Contents/MacOS
chianingku@Chianings-MBP ~ % sudo ./Blender
Password:
sudo: ./Blender: command not found
chianingku@Chianings-MBP ~ % 

Please help me~

**Comment by cgtinker** [comment]
Hey there,

Seems like U are using MacOS and don't have blender installed at the default location.

Navigate to Ur blender exe, right click it and choose: Show Package Contents. Then navigate to contents/MacOs. In there U should find the actual exe.

Open the terminal, and type 'cd' (space) the  drag and drop the executable in the terminal window. Press enter. Then type 'sudo ./blender'.

Once the dependencies are installed and you have given Ur terminal camera privileges you can use ./blender to start blender and use Blendarmocap. (Sadly MacOS is very restrictive when it comes to it's camera usage therefore it's required to run the add-on using the terminal)

**Comment by elastikukk** [comment]
success!!!!!!!Thank you very very verrrrrry much haha
