### ISSUE TITLE
Webcam popup UI text invisible

### ISSUE THREAD

**Issue by Zekiah-A** [cgtinker/BlendArMocap#8]
![image](https://user-images.githubusercontent.com/73035340/152651451-37ded293-8954-43f2-924c-5bd2007a305b.png)
The text on the buttons here seems to not be displaying properly, I am using arch linux with the GNOME desktop environment.

**Comment by cgtinker** [comment]
Not sure if I can fix that, based on the information this issue is based on opencv on arch linux. Does it influence the tracking or closing the window with the 'Q' button?

**Comment by Zekiah-A** [comment]
> Not sure if I can fix that, based on the information this issue is based on opencv on arch linux. Does it influence the tracking or closing the window with the 'Q' button?

No. All features of it seem to still work fine, but it just makes it quite tricky to use, I'll have a look myself at if there are any fixes for this.
