### ISSUE TITLE
Hands are not detected

### ISSUE THREAD

**Issue by gagashaggy** [cgtinker/BlendArMocap#80]
Hello, we are trying to use BlendArMocup for sign language. However, the Hands module doesn't seem to work. When we select Hands as target and start detection, it doesn't create any vertices for hands, though in the video window the hands are detected. And when we click Transfer animation, nothing happens. But if we use other modules, they work properly. Only in Holistic, hands also remain motionless. We tried different versions of Blender (3.2, 3.0 and 2.9) and different OS (Windows and Linux) and everywhere result is the same.

**Comment by layerbag** [comment]
I had the same problem, but when I downloaded the addon through gumroad it worked!

**Comment by gagashaggy** [comment]
> I had the same problem, but when I downloaded the addon through gumroad it worked!

Can you please explain how to do it?

**Comment by layerbag** [comment]
go to this website https://cgtinker.gumroad.com/l/rotom and in the text box writen "name a fair price" you can write some value if you want to support the developer, or put an 0 on it to get for free. After that is just click on purchase and download it. The installation is the same process.

**Comment by tarasrumezhak** [comment]
> go to this website https://cgtinker.gumroad.com/l/rotom and in the text box writen "name a fair price" you can write some value if you want to support the developer, or put an 0 on it to get for free. After that is just click on purchase and download it. The installation is the same process.

Which version did you download?

**Comment by layerbag** [comment]
version 1.5.2

**Comment by RAD531** [comment]
> version 1.5.2

I’ve also run into this issue where pose and face work fine but hands do not. Unfortunately, the author doesn’t sell on Gumroad anymore so I can’t use that version. I'm simply using the current repo. Is this a current bug or just on my machine?

**Comment by Tung-Vinh-Long** [comment]
> truy cập trang web này https://cgtinker.gumroad.com/l/rotom và trong hộp văn bản được viết "đặt tên cho giá hợp lý", bạn có thể viết một số giá trị nếu bạn muốn hỗ trợ nhà phát triển hoặc đặt 0 vào đó để nhận miễn phí. Sau đó, chỉ cần nhấp vào mua hàng và tải xuống. Việc cài đặt là quá trình tương tự.

![image](https://user-images.githubusercontent.com/118338006/205641515-70256813-f675-4e63-83e0-695e01411ddd.png)

**Comment by Tung-Vinh-Long** [comment]
> > phiên bản 1.5.2
> 
> Tôi cũng đã gặp vấn đề này khi tư thế và khuôn mặt hoạt động tốt nhưng tay thì không. Tiếc là tác giả không bán trên Gumroad nữa nên mình không dùng bản đó được. Tôi chỉ đơn giản là sử dụng repo hiện tại. Đây có phải là một lỗi hiện tại hay chỉ trên máy của tôi?

anyone download from github thing like that

**Comment by Tung-Vinh-Long** [comment]
> > version 1.5.2
> 
> I’ve also run into this issue where pose and face work fine but hands do not. Unfortunately, the author doesn’t sell on Gumroad anymore so I can’t use that version. I'm simply using the current repo. Is this a current bug or just on my machine?

anyone download from github thing like that
