### ISSUE TITLE
Getting error while installing on windows 

### ISSUE THREAD

**Issue by aaiguy** [cgtinker/BlendArMocap#81]
Hi , I'm trying to install BlendArMocap addon in windows after pressing install I get some installation error as shown in image 
![Screenshot (57)](https://user-images.githubusercontent.com/99234333/180379142-5428d626-0f53-48f2-b639-7b0bdd816dfb.png)

I opened Blender with administrative access still I'm getting above error related to pip install using sys.process

**Comment by aaiguy** [comment]
@cgtinker hey can you answer this please?

**Comment by cgtinker** [comment]
I don't know this bug, no idea how to reproduce it. Atm I'm working on a standalone executable to get rid of dependency issues in the future. Please copy the log from the system console, maybe there's some valuable information.

Besides, you may install the dependencies manually:
1. Find the path to blenders python binary, to do so, navigate to blenders python console and type the cmd:
``` 
import sys
sys.executable
```
2. Copy the path you've received, then open the terminal and install the dependencies manually:
```
{path_to_blenders_python} -m ensurepip
{path_to_blenders_python} -m pip install protobuf==3.20.0
{path_to_blenders_python} -m pip install opencv-contrib-python==4.5.5.64
{path_to_blenders_python} -m pip install mediapipe==0.8.10
```

**Comment by aaiguy** [comment]
hi @cgtinker thanks for reply, i get none when I execute sys.executable however I found out python binary and installed all depedencies manually but when I try to use addon from sidebar i get installation instruction again  as shown in below screenshot. How to skip this and use addon 
![Screenshot (69)](https://user-images.githubusercontent.com/99234333/182302092-a56ad28d-bf48-417a-b3fb-16065c42c345.png)

and system concsole log error as shown below while installing addons
![Screenshot (70)](https://user-images.githubusercontent.com/99234333/182302173-72f0e2b6-066c-48a3-8acf-ede6aaad77d3.png)

**Comment by aaiguy** [comment]
hi @cgtinker any updates on my followup question?

**Comment by jwestendorp** [comment]
> 2. Copy the path you've received, then open the terminal and install the dependencies manually:
> 
> ```
> {path_to_blenders_python} -m ensurepip
> {path_to_blenders_python} -m pip install protobuf==3.20.0
> {path_to_blenders_python} -m pip install opencv-contrib-python==4.5.5.64
> {path_to_blenders_python} -m pip install mediapipe==0.8.10
> ```
This worked for me. 

@aaiguy is `{path_to_blenders_python} -m ensurepip`  giving any errors? In my case it first said 'site-packages is not writeable'. It would still install the packages, but in the wrong location.  I had to open the terminal as an administrator to fix this issue. 
If you navigate to _{path_to_blenders_python}/lib/site-packages_ in the file explorer, the dependencies should show up here.

**Comment by cgtinker** [comment]
I'm about to release a new version next week you can give it a try on the main branch, if any issues arise please refer to #131
