### ISSUE TITLE
Feature request: BVH Export

### ISSUE THREAD

**Issue by DoctorBlobs** [cgtinker/BlendArMocap#82]
Hi,

Are there any plans to make exporting to .BVH files possible?

**Comment by cgtinker** [comment]
Hey there, I created an additional add-on to make this process possible. 
Checkout [rigify gamerrig extension ](https://github.com/cgtinker/rigify_gamerig_extension).
- detect and animate the generated rig, then link the animation to the meta rig
- bake the animation
- export the metarig as .BVH
