### ISSUE TITLE
Start detection with stream takes close to 5 minutes to bring up camera feed

### ISSUE THREAD

**Issue by StoreBoughtRocketGames** [cgtinker/BlendArMocap#86]
This is less of a bug, and more of a usability issue. It takes a super long time to bring up the camera to start doing motion tracking on my computer. When I started trying to use this plug-in, I initially thought it didn't work at all because it took so long to start up.

Specs
Windows 10
Web cam - Logitech BRIO 4K Pro Webcam

Let me know if you need more information. I think this is a really cool project, and I want to help make it as awesome and smooth as you can make it.

**Comment by cgtinker** [comment]
wow that's a startup time! :1st_place_medal: 
can imagine the cv2 version doesn't work properly with your system. Firstly, you can try to change the stream backend to "cap dshow" in the add-on settings. If that doesn't help, probably downgrade [opencv](https://pypi.org/project/opencv-contrib-python/#history). If you need to do so:

1. Find the python exe which blender uses:
`
// cmds in blenders python console:
import sys
sys.executable
`
2. Then downgrade opencv
`
// in the terminal
{path_to_blenders_pyexe} -m pip uninstall opencv-contrib-python
// just a sample version, no idea which works best on your system
{path_to_blenders_pyexe} -m pip install opencv-contrib-python==4.5.4.60
`

**Comment by StoreBoughtRocketGames** [comment]
Changing the backend to dshow seems to have fixed the issue. Thanks!
