### ISSUE TITLE
An error popped up when I tried to use the Hands, Face and Pose detection

### ISSUE THREAD

**Issue by Shaniman864** [cgtinker/BlendArMocap#87]
I deleted BlendARMocap.  Today I tried to reinstall BlendArMocap, apparently as soon as I installed BlendARMocap into Blender 3.1.  Everything so far is working well but I couldn't use the hands, face and pose detection because an error would pop up.

Please help me because BlendARMocap is a great motion capture program, and I don't want to lose this program.

**Comment by cgtinker** [comment]
Can you toggle your system console and paste the error message here?

**Comment by Shaniman864** [comment]
I also have another question, Is BlendARMocap only meant for a certain version of Blender (like 2.91 for example)?

**Comment by Shaniman864** [comment]
Also when I try to use BlendARMocap in Blender 3.1, Blender has the dependencies for BlendARMocap installed but when I go into the sidebar, the instructions say that I need the Dependencies installed.

**Comment by cgtinker** [comment]
BlendArMocap should support blender 2.9 - 3.4. Initially I've had no idea what's causing this. Can you download the current version from the main-branch and check if this issue still persist? I changed up a lot - also regarding the dependency management. 

I really would love to find a way to not install dependencies within blender. It's pretty frustrating. Sometimes the packages don't work on system and other add-ons sometimes use packages which clash with blendarmocaps.. add-ons requiring external dependencies just don't seem stable.

The updated version still requires external packages..

**Comment by cgtinker** [comment]
I've opened some issues regarding dependencies, please refer to them if the issue still persist in the new version
