### ISSUE TITLE
Rigify character Transfer Animation button greyed out

### ISSUE THREAD

**Issue by StoreBoughtRocketGames** [cgtinker/BlendArMocap#88]
After going through the process of adding a rigify rig to my character the Transfer Animations button is now greyed out and I can't seem to transfer any animations. It still generates the cgt_HANDS, FACE, etc as usual. But I can't seem to get it to transfer the animation anymore.

Before, my first test was with just a rig and rigify, and it seemed to work okay. But once I added a real mesh it stopped allowing animation transfer.

**Comment by cgtinker** [comment]
could it be that you are trying to transfer in pose mode?
transferrng is only supported in object mode.

**Comment by StoreBoughtRocketGames** [comment]
Looks like that was it! Sorry, thought there might be a bug.
