### ISSUE TITLE
BlendArMocap and Make Human (character modeling software ) rigify problem 

### ISSUE THREAD

**Issue by mostafablender** [cgtinker/BlendArMocap#89]
Hi bro . how you doing ? i hope you be fine . 
recently i tried your addon in blender it is amazing  . i also tried to combine it with other  programs and addons . 
first very thing i find "make human" a free  software  that let you make characters with rig   with the plugin this software has  i can import model with rigify rig into blender ( i have to import mhx2 format not the obj or other format )  
from here : http://www.makehumancommunity.org/content/downloads.html
 the plugin to import in blender (with other options like rigify i have to use this plugin here  :
 http://www.makehumancommunity.org/content/plugins.html
 
 after i import the character in blender with rigify rig  i tried to use your addon  it work for hands part but for other parts like face or pose  it give me error . i dont know if it is a bug from your addon or the problem is human character rigify rigs . 

again very thank you for your cool addon .

**Comment by cgtinker** [comment]
Hey, there
the make human character rigs differ from the default humanoid metarig, that's why it hasn't been working. I've been working on an update to support different rigs which will go live soon.
Check #35
