### ISSUE TITLE
Python error when installing in Blender (Win64) as Admin

### ISSUE THREAD

**Issue by wobbleburger** [cgtinker/BlendArMocap#9]
Traceback (most recent call last):
  File "A:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Paimon\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlendArMocap-main\__init__.py", line 41, in <module>
    from utils import log
  File "C:\Users\Paimon\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\utils.py", line 14, in <module>
    from . import maths
ImportError: attempted relative import with no known parent package

I tried in 3.0.1 and 3.1.0

**Comment by cgtinker** [comment]
Do you use a custom start-up scene?

Not sure yet what causes this issue but I'll try to fix it in the upcoming update

**Comment by TACarp** [comment]
I get a similar error on Windows 10 with Blender 2.93.8 when I try enabling the addon.
`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\troyc\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-main\__init__.py", line 41, in <module>
    from utils import log
ImportError: cannot import name 'log' from 'utils' (C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\startup\bl_ui\utils.py)

`

I do use a custom startup scene, but I tried loading factory settings per your advice and to no avail.

**Comment by cgtinker** [comment]
I'm working on a fix. Will be up soon!

**Comment by cgtinker** [comment]
> feed

could you link the error msg?
Working on these issues at the moment.

**Comment by wobbleburger** [comment]
Sure, just a sec - thanks so much for helping

[image: image.png]

**Comment by Calibur25** [comment]
I had an error with installing the python requirements. Would this be caused because I run Blender from a folder and I didn't install it? (I do this because I separate my professional work from my personal work (which is my experimental playground).

**Comment by cgtinker** [comment]
Try the updated version from the main branch, should be fixed now

**Comment by Calibur25** [comment]
> Try the updated version from the main branch, should be fixed now

It worked perfectly. Thank you for your diligence in this matter and showing your passion on this project. It can't be easy.

**Comment by cgtinker** [comment]
> > Try the updated version from the main branch, should be fixed now
> 
> It worked perfectly. Thank you for your diligence in this matter and showing your passion on this project. It can't be easy.

Thanks a lot, glad the update works 🙂
