### ISSUE TITLE
Maybe transfer pose to MetaRig not the Rig

### ISSUE THREAD

**Issue by CGMikeG** [cgtinker/BlendArMocap#90]
Hi,

I can see this addon is definitely heading in the right direction. I hope you don't mind if I recommend attaching the pose to MetaRig and not the rig directly.

I have tried out a few apps and addon and the Generated Rig always have some weird results in comparison to just the Armature. 

I think this is caused by the maths behind the Generated Rig, for the math or program to work, you will have to work you will need to create your own to correct the positioning of the IK, pole position, etc.

But if you transfer directly to the Metarig or Armature it will just work because no external force is affecting the animation.

Also, it will make it easier for users to clean up the animation.

More power to you, and your app. Hopefully, you will continue to work on it.

Although there are lots of motion capture apps currently coming out these days, blender users would very much prefer to process motion capture directly in blender.

Thank you.

**Comment by cgtinker** [comment]
Hey there, I know it's been a while but now it's here. =)
While I'm not transferring directly to the meta rig, you can use my rigify extension here:

https://github.com/cgtinker/rigify_gamerig_extension

You have to select the generated rigify rig, then you'll find options to transfer easily to the meta rig!
I rewrote the entire transfer to support other rigs in the future - you can checkout the addon which is currently at the main branch. I'll have to do some testing before I'll make an official release - but it's already worth to give it go.

Besides, I guess gamers extension solves your needs =)
