### ISSUE TITLE
gopro webcam device stream error

### ISSUE THREAD

**Issue by awfulTHEcode** [cgtinker/BlendArMocap#91]
hello, thanks for this nice dev.
i use my gopro hero9 as webcam with the gopro webcam software (V1.2.1.813) on windows 10 (Pro. 10.0.19044 build 19044)
blender started with elevated rights and the dependencies are installed without error.

slot 0 give me an Traceback Error
Python: Traceback (most recent call last):
  File "C:\Users\awfulTHE2020\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlendArMocap-main\src\cgt_blender\interface\ui_operators.py", line 120, in execute
    self.detection_handler.init_detector(camera_index, dimensions, backend, frame_start, key_step, 0)
  File "C:\Users\awfulTHE2020\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlendArMocap-main\src\main.py", line 115, in init_detector
    self.detector.stream = stream.Webcam(
  File "C:\Users\awfulTHE2020\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlendArMocap-main\src\cgt_utils\stream.py", line 48, in __init__
    raise IOError("Cannot open webcam")
OSError: Cannot open webcam

slot 1-3 reserved by other webcams from different vendors (i didnt have them right now at my hands)

i have to use "Webcam Device Slot 4" after installation of your plugin in blender (V 3.1.0).
the videopicture looks scrambled like this:
![streamdetectionerror_1](https://user-images.githubusercontent.com/110938979/183756961-636b3b6f-ebbc-4329-8f05-326477687cbf.JPG)

is there a way to establish a gopro as input stream?

thanks a ton

**Comment by Tung-Vinh-Long** [comment]
![image](https://user-images.githubusercontent.com/118338006/205639972-1b3fba43-fd34-458d-a39a-88103eb9de76.png)
you can try switching between these 2 modes.
Open it in install add on

**Comment by cgtinker** [comment]
> hello, thanks for this nice dev. i use my gopro hero9 as webcam with the gopro webcam software (V1.2.1.813) on windows 10 (Pro. 10.0.19044 build 19044) blender started with elevated rights and the dependencies are installed without error.
> 
> slot 0 give me an Traceback Error Python: Traceback (most recent call last): File "C:\Users\awfulTHE2020\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlendArMocap-main\src\cgt_blender\interface\ui_operators.py", line 120, in execute self.detection_handler.init_detector(camera_index, dimensions, backend, frame_start, key_step, 0) File "C:\Users\awfulTHE2020\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlendArMocap-main\src\main.py", line 115, in init_detector self.detector.stream = stream.Webcam( File "C:\Users\awfulTHE2020\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\BlendArMocap-main\src\cgt_utils\stream.py", line 48, in **init** raise IOError("Cannot open webcam") OSError: Cannot open webcam
> 
> slot 1-3 reserved by other webcams from different vendors (i didnt have them right now at my hands)
> 
> i have to use "Webcam Device Slot 4" after installation of your plugin in blender (V 3.1.0). the videopicture looks scrambled like this: ![streamdetectionerror_1](https://user-images.githubusercontent.com/110938979/183756961-636b3b6f-ebbc-4329-8f05-326477687cbf.JPG)
> 
> is there a way to establish a gopro as input stream?
> 
> thanks a ton

Sorry for the late response - I just stumbled across this:

https://stackoverflow.com/questions/36112313/how-connect-my-gopro-hero-4-camera-live-stream-to-opencv-using-python

It seems like this is an opencv issue. I don't think it's a good idea installing additional dependencies for such a niche case but probably you can make it work for yourself? :)

You just would have to make some minor changes to `cv_stream.py` and install _goprocam_ via pip.
