### ISSUE TITLE
Stuck when installing BlendARMocap in osx.

### ISSUE THREAD

**Issue by BellaRune** [cgtinker/BlendArMocap#92]
Hi, 
when installing through Terminal in Osx everything is running smoothly, but seems to get stuck:
sorry if this is a banal new question. Can not wait to get into BlendARmocap :)
Thank you

Copy of Terminal:
  Downloading opencv-contrib-python-4.6.0.66.tar.gz (149.9 MB)
     |████████████████████████████████| 149.9 MB 4.7 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.17.3; python_version >= "3.8" in /Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages (from opencv-contrib-python>=4.5.5.64) (1.19.5)
Building wheels for collected packages: opencv-contrib-python
  Building wheel for opencv-contrib-python (PEP 517) ... \

**Comment by cgtinker** [comment]
Hey there, sorry for the late response. 
Which version of OS X you are using?
You are getting stuck at downloading open cv? Is this resolved already?

**Comment by cgtinker** [comment]
closed due to inactivity
