### ISSUE TITLE
RuntimeError: Operator bpy.ops.object.mode_set.poll() context missing active object

### ISSUE THREAD

**Issue by AIMads** [cgtinker/BlendArMocap#95]
First of all thanks for the great work, this is a very exciting tool to use. I experience an issue when i perform a motion capture and transfer it. After I have done that and want to record a new motion capture I experience this error:
<img width="893" alt="image" src="https://user-images.githubusercontent.com/40860899/190168424-dc917ee7-455b-4683-b254-2639dbfeefca.png">

A new motion will be captured and transfered even tho this error pops up. But if you reload the file or remove the drivers, and perform a new motion capture, then the error will happen too but this time it is not possible to transfer the motion.

**Comment by AIMads** [comment]
[NewRigScaledCorrect.blend.zip](https://github.com/cgtinker/BlendArMocap/files/9566795/NewRigScaledCorrect.blend.zip)
Here is the blender file, in case that is usefull?

System is MacOS, with m1 chip. But I have installed the Intel version of blender, to get the lib working

**Comment by cgtinker** [comment]
Can you try the new version on the main branch? I'll create an official release about next week.
1. You should be able to use blenders arm version now.
2. The bug should be fixed
