### ISSUE TITLE
Unable to install mediapipe dependency with Blender v3.3

### ISSUE THREAD

**Issue by johnnyvenom** [cgtinker/BlendArMocap#97]
I've just started using the newest Blender version (3.3) and am trying to install the BlendArMocap add-on. However mediapipe will not install, with the log showing:

```
ERROR: Could not find a version that satisfies the requirement mediapipe>=0.8.10 (from versions: none)
ERROR: No matching distribution found for mediapipe>=0.8.10
```

Blender 3.3 comes with Python 3.10; is the correct mediapipe binary not available? 

For reference, my setup is: 
MacBook Pro M1 Pro
MacOS 12.2.1

**Comment by MONKATRON** [comment]
Same Here.

**Comment by davidroberthoare** [comment]
also on my Macbook Pro (M1, Osx 12.5)
Thanks!

**Comment by Akikannblossom** [comment]
Same problem+1

**Comment by UssamaNaveed** [comment]
I have the same issue unfortunately

**Comment by cgtinker** [comment]
Hey there, I've made a lot of changes - also including the dependency setup. I didn't have access to an arm based apple machine, so I'm not certain if the update will work but you can give it a try already. I'll officially release the update when I'm through with testing.
Mediapipe just released a silicon version (which has to be tested). So far it had been necessary to download the intel version and use rosetta to run the application - you might give the update a go, just pushed it to the main branch.

**Comment by cgtinker** [comment]
@UssamaNaveed @davidroberthoare @johnnyvenom 

> Hey there, I've made a lot of changes - also including the dependency setup. I didn't have access to an arm based apple machine, so I'm not certain if the update will work but you can give it a try already. I'll officially release the update when I'm through with testing.
> Mediapipe just released a silicon version (which has to be tested). So far it had been necessary to download the intel version and use rosetta to run the application - you might give the update a go, just pushed it to the main branch.

did using the version on the main branch solve your issue? I've recently tested in on a m1 - please give it a try.

**Comment by cgtinker** [comment]
please try to current version from the main branch, silicon macs should be supported now. I'll create an official release next week. If you still face issues please refer to #130
