### ISSUE TITLE
generates an error message when I click on the "transfer animation" button

### ISSUE THREAD

**Issue by gbasole** [cgtinker/BlendArMocap#98]
I follow all the steps to the letter until I click on the "transfer animation" button, it generates the following error message:

Report. Error
Python. Traceback (most recent call last):
File "CAUsersilenovo)AppData)Roaming)BlenderFoundation)Blender13.1\scripts\addons)BlendArMocap-mainisre\cgt,blenderinterfacejui_operators.py",line45,inexecute
selected armature = user selected rig.name full
AttributeError: 'NoneType' object has no attribute "name full'
location: sunknown locations:-1

**Comment by cgtinker** [comment]
Hey there, sorry for the late response.
Looks like you didn't select a **generated rigify rig**  as transfer target.
