### ISSUE TITLE
Unable to install dependencies on Windows 10

### ISSUE THREAD

**Issue by looninho** [cgtinker/BlendArMocap#99]
Hi,
I use Blender 3.3 and BlenderArMocap-release-152 under Windows 10.
I run Blender with admin privilege, when I click `Install dependencies` in Blender Preferences window, the push button becomes blue then goes back to grey after some seconds.
Here is my screenshot showing cv2, protobuf, mediapipe  status:
![image](https://user-images.githubusercontent.com/9430758/195068332-e8f8b990-e9f5-48e0-98d4-0e7cdcc88bc2.png)

**Comment by looninho** [comment]
I wonder if the installation folder is blocked. 

I have installed Blender with Microsoft Store so Blender is installed in `C:\Program Files\WindowsApps\`. And it is hard to have access to this folder even for viewing. [https://www.makeuseof.com/windows-access-windowsapps-folder/#:~:text=2.%20How%20to%20Access%20WindowsApps%20via%20a%20Powershell%20Command](url).
I've tried that and also Enable Developer Mode in Windows (and Blender was launched with admin right of course) but still get error in Blender console when installing dependencies:
![image](https://user-images.githubusercontent.com/9430758/195128292-f97caea2-c8e6-42b6-8d38-de467ccd3d1a.png)

These error messages suggest to use `--user` flag. But not possible from this ticket [https://blender.stackexchange.com/questions/181928/does-blender-use-a-python-virtual-environment#:~:text=Current%20state%20of%20Blender%27s%20Python%20integration](url)

So for those who have installed Blender with Microsoft Store, if someone finds an alternative to install dependencies let me know.

**Comment by cgtinker** [comment]
Sorry for the late response, kinda went from my radar. I updated blendarmocap, and while installing dependencies should work better, it's still annoying that it's necessary. Consider to download the current version from the main branch, I'll create an official release next week. Please refer to #131 if any issues arise.
